=== gmulinti/udm-datamodel/json-schemas/src/main/resources/schemas/positionopening.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "http://openplatform.lumesse.com/schemas/positionopening",
	"title": "job / position opening detail",
	"description": "Schema for use case UC003* - details of job / position opening",
	"type": "object",
	"javaType": "com.openplatform.udm.position.PositionOpening",
	"javaInterfaces": ["java.io.Serializable"],
	"properties": {
		"positionID": {
			"description": "identifier of position",
			"type": "array",
			"items": {
				"$ref": "id.json"
			}
		},
		"positionTitle": {
			"description": "title of position",
			"type": "string"
		},
		"positionURI": {
			"description": "URI of position - for detailed view",
			"type": "string"
		},
		"applyURI": {
			"description": "URI for online application (form)",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"applicationMethod": {
			"description": "further methods of application",
			"type": "array",
			"items": {
				"type": "object",
				"javaInterfaces": ["java.io.Serializable"],
				"properties": {
					"target": {
						"description": "Target",
						"type": "string"
					},
					"label": {
						"description": "Label",
						"type": "string"
					}
				},
				"additionalProperties": false
			}
		},
		"positionOpeningStatusCode": {
			"description": "Status of position opening; typical values: 'Active', 'Closed', 'Incomplete'",
			"type": "string"
		},
		"positionSupplier": {
			"description": "Supplier of position - e.g. company, job board",
			"type": "string"
		},
		"positionLocation": {
			"description": "Physical location of the position",
			"type": "array",
			"items": {
				"$ref": "address.json"
			}
		},
		"organizationName": {
			"description": "Organization Name",
			"type": "string"
		},
		"parentOrganizationName": {
			"description": "Parent Organization Name",
			"type": "string"
		},
		"departmentName": {
			"description": "Department Name",
			"type": "string"
		},
		"positionIndustry": {
			"description": "Industry of the position - name/code - relates to field HR-XML 3.2 : PositionOpening",
			"type": "array",
			"items": {
				"$ref": "industrycode.json"
			}
		},
		"jobCategory": {
			"description": "Job category of the position - name/code",
			"type": "array",
			"items": {
				"$ref": "jobcode.json"
			}
		},
		"jobGrade": {
			"description": "Job grade of the position - name/code",
			"type": "array",
			"items": {
				"$ref": "code.json"
			}
		},
		"careerLevel": {
			"description": "Career level of the position - name/code",
			"type": "array",
			"items": {
				"$ref": "code.json"
			}
		},
		"positionSchedule": {
			"description": "Schedule of the position - name/code",
			"type": "array",
			"items": {
				"$ref": "code.json"
			}
		},
		"positionOfferingType": {
			"description": "Offering type of the position - name/code",
			"type": "array",
			"items": {
				"$ref": "code.json"
			}
		},
		"qualificationSummary": {
			"description": "Summary of qualifications relevant for the position. Could include competencies, certificates and licenses",
			"type": "string"
		},
		"positionRemuneration": {
			"description": "Information on remuneration of the position, Contains a minimum/maximum range for a given interval as well as a general description field.",
			"type": "array",
			"items": {
				"type": "object",
				"javaInterfaces": ["java.io.Serializable"],
				"properties": {
					"minimumRange": {
						"description": "Minimum Range",
						"type": "string"
					},
					"maximumRange": {
						"description": "Maximum Range",
						"type": "string"
					},
					"rateIntervalCode": {
						"description": "Rate Interval Code",
						"type": "string"
					},
					"description": {	
						"description": "Description",
						"type": "string"
					},
					"userArea": {
						"description": "The userarea section contains the additional field mapping",
						"type": "array",
						"items": {
							"$ref": "userarea.json"
						}
					}
				},
				"additionalProperties": false
			}
		},
		"workingLanguage": {
			"description": "Information on the position working language - name/code",
			"type": "array",
			"items": {
				"$ref": "languagecode.json"
			}
		},
		"positionStartDate": {
			"description": "Start date of the position",
			"type": "string"
		},
		"positionEndDate": {
			"description": "End date of the position - if limited / not permanent",
			"type": "string"
		},
		"publicationStartDate": {
			"description": "Start date of publication - in current channel",
			"type": "string"
		},
		"applicationCloseDate": {
			"description": "Close date of the application period",
			"type": "string"
		},
		"positionFormattedDescription": {
			"description": "Formatted description texts for the position",
			"type": "array",
			"items": {
				"type": "object",
				"javaInterfaces": ["java.io.Serializable"],
				"properties": {
					"content": {
						"description": "Actual description text",
						"type": "string"
					},
					"label": {
						"description": "Label to describe type of description text - in order to identify relevant parts",
						"type": "string",
						"enum": ["SummaryDescription", "FullDescription", "Snippet", "Keywords", "Other"]
					},
					"labelDescription": {
						"description": "Additional label description to specify usage in detail.",
						"type": "string"
					},
					"userArea": {
						"description": "The userarea section contains the additional field mapping",
						"type": "array",
						"items": {
							"$ref": "userarea.json"
						}
					}
				},
				"additionalProperties": false
			}
		},
		"postingInstruction": {
			"description": "",
			"type": "array",
			"items": {
				"type": "object",
				"javaInterfaces": ["java.io.Serializable"],
				"properties": {
					"templateID": {
						"description": "",
						"type": "string"
					},
					"brandingID": {
						"description": "",
						"type": "string"
					},
					"logoURI": {
						"description": "",
						"type": "string"
					},
					"userArea": {
						"description": "The userarea section contains the additional field mapping",
						"type": "array",
						"items": {
							"$ref": "userarea.json"
						}
					}
				}
			}
		},
		"specialCommitment": {
			"description": "Additional information on special commitments - name/code",
			"type": "array",
			"items": {
				"$ref": "code.json"
			}
		},
		"attachment": {
			"description": "Attachment",
			"type": "array",
			"items": {
				"$ref": "attachment.json"				
			}
		},
		"userArea": {
			"description": "The userarea section contains the additional field mapping",
			"type": "array",
			"items": {
				"$ref": "userarea.json"
			}
		}
	},
	"additionalProperties": false
}

=== gmulinti/udm-datamodel/json-schemas/src/main/resources/sample/position.sample.json
{
  "positionID": [
    {
      "id": "23",
      "scheme": "PostingPositionID"
    }
  ],
  "positionTitle": "Software Developer",
  "positionURI": "http://crmsystem.com/jobs/lumesse/264",
  "applyURI": [
    "http://crmsystem.com/jobs/lumesse/264/apply"
  ],
  "applicationMethod": [
    {
      "target": "Lumesse Job Portal",
      "label": "http://lumesse.com/jobs/softwaredeveloper2"
    }
  ],
  "positionOpeningStatusCode": "Active",
  "positionSupplier": "Company",
  "positionLocation": [
    {}
  ],
  "organizationName": "Lumesse",
  "parentOrganizationName": "N/A",
  "departmentName": "R&D",
  "positionIndustry": [
    {
      "name": "Computer Software",
      "code": "1234"
    }
  ],
  "jobCategory": [
    {
      "name": "Technology",
      "code": "http://ec.europa.eu/esco/occupation/"
    }
  ],
  "jobGrade": [
    {
      "name": "Level",
      "code": "Manager"
    }
  ],
  "careerLevel": [
    {
      "name": "Level",
      "code": "Senior"
    }
  ],
  "positionSchedule": [
    {
      "name": "Standard 9 to 5",
      "code": "9T5"
    }
  ],
  "positionOfferingType": [
    {
      "name": "Full Time",
      "code": "FT"
    }
  ],
  "qualificationSummary": "BSc",
  "positionRemuneration": [
    {
      "minimumRange": "40000",
      "maximumRange": "60000",
      "rateIntervalCode": "Year",
      "description": "Gross pay"
    }
  ],
  "workingLanguage": [
    {
      "name": "English",
      "code": "ENG"
    }
  ],
  "positionStartDate": "12/01/2015",
  "positionEndDate": "12/01/2016",
  "publicationStartDate": "6/1/2015",
  "applicationCloseDate": "6/2/2015",
  "positionFormattedDescription": [
    {
      "content": "A software developer opportunity in Lumesse's R&D department",
      "label": "SummaryDescription",
      "labelDescription": "Title"
    }
  ],
  "postingInstruction": [
    {
      "templateID": "Standard layout",
      "brandingID": "Lumesse logo",
      "logoURI": "Lumesse 200x100"
    }
  ],
  "specialCommitment": [
    {
      "name": "Manage team of existing developers",
      "code": "MAN"
    }
  ],
  "attachment": [
    {
      "embeddedData": "SSB3cml0ZSB0aGlzIGNvdmVyIGxldHRlciBpbiBjb25qdW5jdGlvbiB3aXRoIG15IENWIHRvIGFkZCBmdXJ0aGVyIGRldGFpbHMgYWJvdXQgbXkgY2FyZWVyIHRvIGRhdGUgYW5kIEkgd2h5IEkgdGhpbmsgSSB3b3VsZCBiZSBhIGdvb2QgZml0IGZvciB0aGUgcm9sZSB5b3UgYXJlIGFkdmVydGlzaW5nLiBUaGUgdmFzdCBtYWpvcml0eSBvZiBteSBjYXJlZXIgaGFzIGZvY3VzZWQgb24uLi4=",
      "embeddedText": "I write this cover letter in conjunction with my CV to add further details about my career to date and I why I think I would be a good fit for the role you are advertising. The vast majority of my career has focused on...",
      "uri": "http://candidateattachments/repository/candidate3245/CoverLetter.doc",
      "fileName": "CoverLetter.doc",
      "description": "Cover letter",
      "fileType": "Doc",
      "documentTitle": "Cover letter for software developer role at Lumesse",
      "accessCredentials": [
        {
          "userID": "65372",
          "typeCode": [
            {
              "name": "Username & password",
              "code": "UAP",
              "codeURI": "http://isocodes/accesscredtype",
              "codeType": "http://isocodes/accesscredtype/#code-a1"
            }
          ],
          "value": "username: Username, password: LumessePass1"
        }
      ],
      "userArea": [
        {
          "key": "middleName",
          "value": "bob"
        }
      ]
    }
  ]
}
